import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";
import ToastProvider from "@/components/ToastProvider";
import Footer from "@/components/Footer";
import SmallFooter from "@/components/SmallFooter";

// Importing custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for SEO
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <Suspense fallback={<div className="w-full h-screen grid place-content-center">
          Loading...
        </div>}>
          <ToastProvider>
            <div className="min-h-screen bg-gradient-to-r from-green-100 to-blue-100">
              {children}
            </div>
          </ToastProvider>
        </Suspense>
      </body>
    </html>
  );
}
